server:
  port: 7070

product:
  cache:
    strategy: KEY_BASED
    capacity: 1000

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/productsvcdb
flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration